channels:
- conda-forge
dependencies:
- python=3.11.11
- pip<=24.1.2
- pip:
  - mlflow==2.20.0
  - cffi==1.17.1
  - cloudpickle==3.1.1
  - cupy-cuda12x==12.2.0
  - dask==2024.10.0
  - defusedxml==0.7.1
  - graphviz==0.20.3
  - imbalanced-learn==0.13.0
  - jinja2==3.1.5
  - lightgbm==4.5.0
  - matplotlib==3.10.0
  - numpy==1.26.4
  - pandas==2.2.2
  - pathlib==1.0.1
  - psutil==5.9.5
  - pyarrow==17.0.0
  - pytest==8.3.4
  - scikit-learn==1.6.1
  - scipy==1.13.1
  - zstandard==0.23.0
name: mlflow-env
